name: pre-checks

on:
  push:
    branches:
      - main
    tags:
      - v*.**
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Lint commit message
        uses: csaf-rs/shared-workflows/.github/actions/commitlint@961946fcc07ac8d8556b6afbd13f62a93a4c1bc1 # TODO: Update to release
