name: pre-checks

on:
  push:
    branches:
      - main
    tags:
      - v*.**
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Lint commit message
        uses: csaf-rs/shared-workflows/.github/actions/commitlint@f50ba33c55b84b6b0da4c45c1814d1cf82c64f0e # TODO: Update to release
